2024-07-09 09:58:58,659 - logs.logs - INFO - Calling hello with args: (), kwargs: {}
2024-07-09 09:59:21,817 - logs.logs - INFO - Calling hello with args: (), kwargs: {}
2024-07-09 09:59:21,817 - logs.logs - INFO - There was an exception in  hello
2024-07-09 09:59:21,817 - logs.logs - ERROR - There was an exception in  hello
Traceback (most recent call last):
  File "/Users/olopezdoriga/Desktop/GH_repos/beacon-production-prototype/beacon-production-prototype/logs/logs.py", line 35, in wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
TypeError: hello() missing 1 required positional argument: 'request'
2024-07-09 09:59:31,986 - logs.logs - INFO - Calling hello with args: (), kwargs: {}
2024-07-09 09:59:31,986 - logs.logs - INFO - hello returned: {'status': 'hello'}
2024-07-09 09:59:51,288 - logs.logs - INFO - Calling hello with args: (), kwargs: {}
2024-07-09 09:59:51,288 - /Users/olopezdoriga/Desktop/GH_repos/beacon-production-prototype/beacon-production-prototype/logs/logs.py - 34 - Calling hello with args: (), kwargs: {}
2024-07-09 09:59:51,288 - logs.logs - INFO - hello returned: {'status': 'hello'}
2024-07-09 09:59:51,288 - /Users/olopezdoriga/Desktop/GH_repos/beacon-production-prototype/beacon-production-prototype/logs/logs.py - 36 - hello returned: {'status': 'hello'}
2024-07-09 10:00:13,049 - logs.logs - INFO - Calling hello with args: (), kwargs: {}
2024-07-09 10:00:13,049 - logs.logs - INFO - hello returned: {'status': 'hello'}
